package com.example.mentalhealth;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link MoodFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class MoodFragment extends Fragment {


    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";


    // creating variables for our edittext, button and dbhandler
    private EditText moodRatingEdt, moodDateEdt, moodDescriptionEdt, oldDescriptionEdt;
    private Button  readMoodBtn, deleteAllMoodsBtn;
    public MoodDBHelper MooddbHelper;


    Adapter adapter;

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    /**
     * empty constructor is added.
     */
    public MoodFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment MoodFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static MoodFragment newInstance(String param1, String param2) {
        MoodFragment fragment = new MoodFragment();
        Bundle args = new Bundle();
        return fragment;
    }

    /**
     * Autogenerated function.
     * @param savedInstanceState
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    }

    /**
     * Creates the view and controls the data of update and delete.
     * @param inflater
     * @param container
     * @param savedInstanceState
     * @return
     */
    @SuppressLint("MissingInflatedId")
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        super.onCreate(savedInstanceState);

        View view=inflater.inflate(R.layout.fragment_mood, container, false);


        // initializing all our variables.
        moodRatingEdt = view.findViewById(R.id.idEdtMoodRating);
        moodDescriptionEdt = view.findViewById(R.id.idEdtMoodDescription);
        moodDateEdt = view.findViewById(R.id.idDate);
        oldDescriptionEdt = view.findViewById(R.id.idEdtOldMoodDescription);


        readMoodBtn = view.findViewById(R.id.idBtnReadMood);
        deleteAllMoodsBtn = view.findViewById(R.id.idBtnDeleteAllMoods);


        // creating a new dbhandler class
        // and passing our context to it.
        MooddbHelper = new MoodDBHelper(view.getContext());


        readMoodBtn.setOnClickListener(new View.OnClickListener() {
            /**
             * Read all the data from the mood.
             * @param v
             */
            @Override
            public void onClick(View v) {
                // opening a new activity via a intent.
                ListView l;
                // getting our course array
                // list from db handler class.
                ArrayList<MoodModal> MoodModalArrayList;
                MoodModalArrayList = MooddbHelper.readMoods();

                ArrayList<String >Mood_list_data = new ArrayList<String>();

                // store it inside an arraylist.
                for(MoodModal i: MoodModalArrayList){
                    String temp ="Date: " + i.getDate() + ", Mood Rating: " + i.getMoodRating()+"\n"+  "Description: "+i.getMoodDescription();

                    Mood_list_data.add(temp);
                }

                // Create the view and present the list.
                l = view.findViewById(R.id.list);
                ArrayAdapter<String> arr;
                arr = new ArrayAdapter<String>(view.getContext(), androidx.appcompat.R.layout.support_simple_spinner_dropdown_item, Mood_list_data);
                l.setAdapter(arr);


            }
        });

        deleteAllMoodsBtn.setOnClickListener(new View.OnClickListener() {
            /**
             * delete the specific mood entry.
             * @param v
             */
            public void onClick(View v){

                String moodDescription = oldDescriptionEdt.getText().toString();
                MooddbHelper.deleteMood(moodDescription);
                oldDescriptionEdt.setText("");
            }
        });




       adapter=new Adapter(view.getContext());



        return view;
    }
}